"""empty message

Revision ID: 204e5b9f1361
Revises: 0cb708d62b39
Create Date: 2024-10-04 14:32:51.841787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204e5b9f1361'
down_revision = '0cb708d62b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_queues',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_user_queues_queue_id_queues')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_queues_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'queue_id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    op.drop_table('user_queues')
    # ### end Alembic commands ###
