"""empty message

Revision ID: a3f1ae595ef8
Revises: 204e5b9f1361
Create Date: 2024-10-04 16:38:42.314891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f1ae595ef8'
down_revision = '204e5b9f1361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_queues',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_ticket_queues_queue_id_queues')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_queues_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('ticket_id', 'queue_id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_queue_id_queues', type_='foreignkey')
        batch_op.drop_column('queue_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_tickets_queue_id_queues', 'queues', ['queue_id'], ['id'])

    op.drop_table('ticket_queues')
    # ### end Alembic commands ###
